### PR TITLE
[HOPS-1118] Database query fails for large number of buckets per data…

### PR DESCRIPTION
**Pull request by smkniazi**
…node

## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-1118

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bugfix

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
https://github.com/hopshadoop/hops-metadata-dal/pull/153

### CODE REVIEW

**Comment by berthoug** [comment]
Wouldn't an intermediary solution that still makes requests in batches but limit the size of the batches be more efficient?

**Comment by smkniazi** [comment]
We can not use batching as we do not  know what is in the bucket on the NN side. So each bucket has to be scanned. Now we scan one bucket at a time to reduce the amount of data read in each operation instead of scanning all buckets  in one operation.

**Comment by berthoug** [comment]
Can you check TestDataNodeVolumeFailureReporting?

**Comment by berthoug** [comment]
tests: https://bbc1.sics.se/jenkins/view/pull-manual/job/hops-pull-manual/59/

**Comment by smkniazi** [comment]
TestDataNodeVolumeFailureReporting also fails on the master branch but not as frequently as after this fix. I am looking into it.

**Comment by berthoug** [comment]
Any progress?

**Comment by smkniazi** [comment]
The test is failing due to some weird synchronization issue.  I have spent a day on it and I could not fix it. I will give it an other try after I am done with the User/Groups Cache Jira

**Pull request merged**
