### PR TITLE
[HOPS-1540] Bump mysql from 5.1.18 -> 8.0.18

### PR DESCRIPTION
**Pull request by smkniazi**
## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
 https://hopshadoop.atlassian.net/browse/HOPS-1540
 
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

You need to also merge this 
https://github.com/logicalclocks/hops-hadoop-chef/pull/173

### CODE REVIEW

**Comment by smkniazi** [comment]
https://bbc1.sics.se/jenkins/job/dist-test/100

**Comment by berthoug** [comment]
Will this create a compatibility problem with hopsworks?

**Comment by smkniazi** [comment]
Yes. Dont merge this right now as it is needed only for newer version of NDB.

**Comment by berthoug** [comment]
Done  by HOPS-1581

**Pull request closed without merging**
